### ISSUE TITLE
Error in testing part

### ISSUE THREAD

**Issue by bharadwajdhornala** [happylun/SketchModeling#13]
@happylun I have installed libraries according to your README. I get this error when I test the main.py on chair data. I have tried some attempts for solving this error but those doesn't work. Please help.

(SKetchModelling) C:\GenAssi\SketchModeling\Network\code\MonsterNet>python main.py --test --data_dir C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\ --train_dir C:\GenAssi\SketchModeling\Checkpoint\Chair\ --test_dir C:\GenAssi\SketchModeling\chair_results\
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:457: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
start running...
Loading testing data...
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Building network...
Testing...

_W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-S-0.png : The system cannot find the file specified.

W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-F-0.png : The system cannot find the file specified._

Traceback (most recent call last):
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
         [[Node: batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 153, in <module>
    tf.app.run()
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 142, in main
    monnet.test(sess, views, num_test_shapes)
  File "C:\GenAssi\SketchModeling\Network\code\MonsterNet\monnet.py", line 471, in test
    names,results,errors,images = sess.run([self.names, self.results, self.errors, self.pngs])
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\dhornala.bharadwaj\AppData\Local\Continuum\anaconda3\envs\SKetchModelling\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch/fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
         [[Node: batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]**

**Comment by happylun** [comment]
I see this warning from your command line output:

> W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Not found: Can not get size for: C:\GenAssi\SketchModeling\zhaoliang_lun_trainingdata\Chair\sketch/03001627/264322794651490ec0d3c02f7e255b2b/sketch-S-0.png : The system cannot find the file specified.

Can you make sure you have that file in this path?

I also see a bunch of errors for unknown Tensorflow ops. Not sure if that is because my code is using a very old version of Tensorflow.

**Comment by bharadwajdhornala** [comment]
I have set my test-list with two rows with 03001627/264322794651490ec0d3c02f7e255b2b and other file. I have checked again this path contains Sketch-S-0 and Sketch-F-0 files.
I am using same tensorflow versin mentioned.

**Comment by wangqiang9** [comment]
> I have set my test-list with two rows with 03001627/264322794651490ec0d3c02f7e255b2b and other file. I have checked again this path contains Sketch-S-0 and Sketch-F-0 files.
> I am using same tensorflow versin mentioned.

if you change the https://github.com/happylun/SketchModeling/blob/3dd6a341b8aeea1367fe4470600f8cbfd45dac03/Network/code/MonsterNet/main.py#L51, change the FS to TS, this bug will be sloved!
